import { ChildProps } from '@/types'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Toaster } from 'sonner'
import './globals.css'
import { languages } from '@/i18n/settings'
import { dir } from 'i18next'
import Logo from './(root)/_components/logo'
import Navbar from './(root)/_components/navbar'

const mailSans = localFont({
	src: [
		{ path: './fonts/MailSansRoman-Light.ttf', weight: '300' },
		{ path: './fonts/MailSansRoman-Regular.ttf', weight: '400' },
		{ path: './fonts/MailSansRoman-Medium.ttf', weight: '500' },
		{ path: './fonts/MailSansRoman-DemiBold.ttf', weight: '600' },
		{ path: './fonts/MailSansRoman-Bold.ttf', weight: '700' },
	],
	variable: '--font-mail-sans',
})

export async function generateStaticParams() {
	return languages.map(lng => ({ lng }))
}

interface Props extends ChildProps {
	params: { lng: string }
}

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children, params: { lng } }: Props) {
	return (
		<html lang={lng} dir={dir(lng)} suppressHydrationWarning>
			<body
				className={`${mailSans.variable} antialiased`}
				suppressHydrationWarning
			>
				<Logo />
				<Toaster />
				<div className='relative mb-16'>{children}</div>
				<Navbar />
			</body>
		</html>
	)
}
